$script = <<-'SCRIPT'
# Install LXC
sudo apt-get install lxc lxc-templates -y
# Only need for Centos/Rhel containers
sudo apt-get install yum -y
# Network for LXC
sudo cat > /etc/default/lxc-net << EOF
USE_LXC_BRIDGE="true"
LXC_BRIDGE="lxcbr0"
LXC_ADDR="10.0.3.1"
LXC_NETMASK="255.255.255.0"
LXC_NETWORK="10.0.3.0/24"
LXC_DHCP_RANGE="10.0.3.2,10.0.3.254"
LXC_DHCP_MAX="253"
LXC_DHCP_CONFILE=""
LXC_DOMAIN=""
EOF
# Enable net 
sudo systemctl enable lxc-net
sudo systemctl start lxc-net
# Default config network for LXC
sudo sed -i 's/lxc.net.0.type = empty/lxc.net.0.type  = veth\nlxc.net.0.flags = up\nlxc.net.0.link  = lxcbr0\n/' /etc/lxc/default.conf
# Create and start Linux Container
sudo lxc-create -n web_static -t centos
sudo lxc-start -n web_static
# Wait after start 10 sec
sleep 10
### INSIDE LXC
# Install need packages
sudo lxc-attach -n web_static -- yum -y install httpd git
# Clone Projects to /var/www/html
sudo lxc-attach -n web_static -- git clone https://github.com/Fenikks/itacademy-devops-files /var/www/html
# Add to httpd Listen 8080
sudo lxc-attach -n web_static -- sed -i 's/Listen 80/Listen 80\nListen 8080/' /etc/httpd/conf/httpd.conf
# Create 2nd container: web_dynamic
sudo lxc-stop -n web_static 
sudo lxc-copy -n web_static -N web_dynamic
sudo lxc-start -n web_static
sudo lxc-start -n web_dynamic
# Wait after start 10 sec
sleep 10
# Create VirtualHost for 8080 port for web_static
sudo cat > /var/lib/lxc/web_static/rootfs/etc/httpd/conf.d/it_academy.conf << EOF
<VirtualHost *:8080>
DocumentRoot /var/www/html/01-demosite-static
</VirtualHost>
EOF
# Create VirtualHost for 8080 port for web_dynamic
sudo cat > /var/lib/lxc/web_dynamic/rootfs/etc/httpd/conf.d/it_academy.conf << EOF
<VirtualHost *:8080>
DocumentRoot /var/www/html/01-demosite-php
</VirtualHost>
EOF
# Install php in LXC web_dynamic
sudo lxc-attach -n web_dynamic -- yum -y install php
# Restart httpd
sudo lxc-attach -n web_static -- systemctl restart httpd
sudo lxc-attach -n web_dynamic -- systemctl restart httpd
SCRIPT

$lxc_test = <<SETUP
echo "FOR TESTING - RUN ALWAYS"
ip_web_dynamic=`sudo lxc-info -n web_dynamic -iH`
ip_web_static=`sudo lxc-info -n web_static -iH`
sudo curl $ip_web_static:8080
sudo curl $ip_web_dynamic:8080
SETUP

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provision "shell", inline: $script
  config.vm.provision "shell", run: "always", inline: $lxc_test
end
