Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/focal64"
 config.vm.synced_folder ".", "/vagrant"
 config.vm.hostname = "ubuntu-focal"
 config.vm.network "forwarded_port", guest: 8080, host: 8080

 config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "playbook.yml"
 end
 
  config.vm.provider "virtualbox" do |v|
   v.memory = 2048
   v.cpus = 4
  end

end
