Vagrant.configure("2") do |config|
 config.vm.box = "yurynaumovich/Centos8_httpd_php_mysql-server"
 config.vm.synced_folder ".", "/vagrant"
 config.vm.network "forwarded_port", guest: 8080, host: 8080
 config.vm.network "forwarded_port", guest: 8081, host: 8081

 config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "/vagrant/playbook.yml"
 end

end
