version: "3.3"
services:
  
  jenkins:
    build: jenkins/
    privileged: true
    ports: 
      - "8080:8080"
        #volumes:
        #- /vagrant/jenkins/jenkins:/var/lib/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/var/lib/jenkins/workspace/
      - /vagrant:/vagrant

    networks:
      bridge:
      vagrant:
        ipv4_address: 192.168.56.100
    depends_on: 
      - nexus
        

  nexus:
    build: nexus/
    ports:
      - "8081:8081"
    #volumes: 
      #- /vagrant/nexus/nexus-data:/nexus-data
    networks:
      bridge:
      vagrant:
        ipv4_address: 192.168.56.101
    hostname: nexus


networks:
  bridge:
  vagrant:
     driver: bridge
     ipam: 
       config:
       - subnet: 192.168.56.0/24

volumes:
  workspace:
