BOX_IMAGE = "generic/centos8"
PLAYBOOK = "playbook.yml"
SLAVE_COUNT = 2
MASTER = "master.puppet"
MASTER_IP = "192.168.56.254"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.synced_folder ".", "/vagrant"
  ENV['LC_ALL']="en_US.UTF-8"

  config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = PLAYBOOK
end

  config.vm.define MASTER do |subconfig|
  subconfig.vm.hostname = "master"
  subconfig.vm.network "private_network", ip: MASTER_IP, hostname: true
  subconfig.vm.provision "shell", inline: <<-SHELL
sudo cat > /etc/sysctl.d/70-ipv6.conf << EOF
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF
sudo sysctl --load /etc/sysctl.d/70-ipv6.conf
SHELL
  subconfig.vm.network "forwarded_port", guest: 81, host: 8082
  subconfig.vm.network "forwarded_port", guest: 82, host: 8083
end

  (1..SLAVE_COUNT).each do |i|
   config.vm.define "slave#{i}.puppet" do |subconfig|
   subconfig.vm.network "private_network", ip: "192.168.56.#{i}", hostname: true
   subconfig.vm.hostname = "slave#{i}.puppet"
   if i == 1
   subconfig.vm.network "forwarded_port", guest: 8080, host: 8080
   elsif i == 2
   subconfig.vm.network "forwarded_port", guest: 8008, host: 8081
   end
end
   
  end
end
