$docker_install = <<-'SCRIPT'
sudo apt-get update && sudo apt-get upgarde
apt-get install docker.io docker-compose -y
# Docker without sudo
sudo gpasswd -a vagrant docker
newgrp docker
# Minicube install
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb
minikube start --driver=docker
alias k="minikube kubectl --"
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.hostname = "kubernets"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: $docker_install
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

end
