Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/focal64"
 config.vm.synced_folder ".", "/vagrant"
 config.vm.hostname = "ubuntu-focal"
 config.vm.network "forwarded_port", guest: 8080, host: 8080
 config.vm.network "forwarded_port", guest: 8081, host: 8081

 config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "lxc_playbook.yml"
 end

end
