$docker_install = <<-'SCRIPT'
sudo apt-get update && sudo apt-get upgarde
apt-get install docker.io -y
# Docker without sudo
sudo gpasswd -a vagrant docker
newgrp docker
SCRIPT

Vagrant.configure("2") do |config|
 config.vm.box = "generic/debian11"
 config.vm.hostname = "docker"
 config.vm.provision "shell", inline: $docker_install
end
